/**
 * AIInsightsPanel — AI Decision Support panel for disruption investigation.
 *
 * ARCHITECTURE CONTRACT:
 *   - The "System Facts" section displays DETERMINISTIC values from the
 *     SupplyShield backend engine. These are never generated by the AI.
 *   - The "AI Analysis" section displays IBM watsonx.ai generated text.
 *   - When watsonx is not configured, the AI section shows a clear
 *     configuration notice. The system facts section is always visible.
 *   - When watsonx fails, an error state is shown without crashing the panel.
 *
 * The visual separation between deterministic and AI-generated content is
 * intentional and must be preserved in any future modifications.
 */

import { useEffect, useState, useCallback } from 'react'
import { disruptionsApi, type AIInsightsResponse } from '../api/disruptions'

interface Props {
  disruptionId: number
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function fmtUSD(n: number | null | undefined): string {
  if (n === null || n === undefined) return '—'
  if (n >= 1_000_000) return `$${(n / 1_000_000).toFixed(1)}M`
  if (n >= 1_000) return `$${(n / 1_000).toFixed(0)}K`
  return `$${n.toFixed(0)}`
}

function fmtPct(n: number | null | undefined): string {
  if (n === null || n === undefined) return '—'
  return `${(n * 100).toFixed(0)}%`
}

function RRIStatusBadge({ status }: { status: string | null | undefined }) {
  if (!status) return <span className="text-gray-600">—</span>
  const colorMap: Record<string, string> = {
    HEALTHY:    'text-green-400 bg-green-900/30 border-green-700',
    STRESSED:   'text-yellow-400 bg-yellow-900/30 border-yellow-700',
    VULNERABLE: 'text-orange-400 bg-orange-900/30 border-orange-700',
    CRITICAL:   'text-red-400 bg-red-900/30 border-red-700',
    BANKRUPT:   'text-red-300 bg-red-950 border-red-800 font-bold',
  }
  const cls = colorMap[status] ?? 'text-gray-400 bg-gray-800 border-gray-700'
  return (
    <span className={`text-[10px] font-semibold px-1.5 py-0.5 rounded border uppercase ${cls}`}>
      {status}
    </span>
  )
}

// ── Sub-components ────────────────────────────────────────────────────────────

function SectionHeader({
  label,
  badge,
  badgeColor = 'bg-gray-700 text-gray-400',
}: {
  label: string
  badge: string
  badgeColor?: string
}) {
  return (
    <div className="flex items-center gap-2 mb-3">
      <span className="text-[10px] font-bold uppercase tracking-widest text-gray-500">
        {label}
      </span>
      <span className={`text-[9px] font-semibold px-1.5 py-0.5 rounded uppercase tracking-wide ${badgeColor}`}>
        {badge}
      </span>
    </div>
  )
}

function FactRow({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div className="flex items-start justify-between gap-2 py-1 border-b border-gray-800/60 last:border-0">
      <span className="text-[11px] text-gray-500 shrink-0">{label}</span>
      <span className="text-[11px] text-gray-200 text-right">{value}</span>
    </div>
  )
}

function SystemFactsSection({ facts }: { facts: Record<string, unknown> }) {
  return (
    <div className="rounded-lg border border-blue-900/40 bg-blue-950/10 p-4">
      <SectionHeader
        label="System Facts"
        badge="Deterministic"
        badgeColor="bg-blue-900/50 text-blue-400 border border-blue-700/50"
      />
      <div className="space-y-0">
        <FactRow
          label="Disruption"
          value={
            <span className="font-mono text-blue-300">
              {String(facts.disruption_code ?? '—')}
            </span>
          }
        />
        <FactRow
          label="Severity"
          value={`${facts.severity ?? '—'}/10`}
        />
        <FactRow
          label="Cargo Exposure"
          value={fmtUSD(facts.total_cargo_exposure_usd as number | null)}
        />
        <FactRow
          label="Shipments Affected"
          value={String(facts.affected_shipment_count ?? '—')}
        />
        <FactRow
          label="Total Delay"
          value={`${facts.total_delay_hours ?? '—'}h`}
        />
        <FactRow
          label="Geographic Scope"
          value={String(facts.geo_scope ?? '—')}
        />
        <FactRow
          label="Transport Mode"
          value={String(facts.transport_mode ?? '—')}
        />
        {Boolean(facts.priority_shipment_code) && (
          <>
            <div className="pt-2 mt-1">
              <p className="text-[9px] uppercase tracking-widest text-gray-600 mb-1">
                Priority Shipment
              </p>
            </div>
            <FactRow
              label="Shipment"
              value={
                <span className="font-mono text-shield-300">
                  {String(facts.priority_shipment_code)}
                  {Boolean(facts.priority_shipment_is_cold_chain) && (
                    <span className="ml-1 text-[9px] text-cyan-400">COLD</span>
                  )}
                </span>
              }
            />
            <FactRow
              label="RRI"
              value={
                <span className="flex items-center gap-1.5">
                  <span className="font-semibold">
                    {typeof facts.priority_shipment_rri === 'number'
                      ? facts.priority_shipment_rri.toFixed(1)
                      : '—'}
                  </span>
                  <RRIStatusBadge status={facts.priority_shipment_rri_status as string} />
                </span>
              }
            />
            <FactRow
              label="Cargo Value"
              value={fmtUSD(facts.priority_shipment_cargo_usd as number | null)}
            />
            <FactRow
              label="Impact Score"
              value={fmtPct(facts.priority_shipment_impact_score as number | null)}
            />
            {facts.most_depleted_dimension && (
              <FactRow
                label="Most Depleted"
                value={
                  <span>
                    <span className="uppercase text-amber-400 font-medium">
                      {String(facts.most_depleted_dimension)}
                    </span>
                    {typeof facts.most_depleted_score === 'number' && (
                      <span className="text-gray-500 ml-1">
                        ({facts.most_depleted_score.toFixed(0)}% remaining)
                      </span>
                    )}
                  </span>
                }
              />
            )}
          </>
        )}
        {Boolean(facts.top_similar_disruption) && (
          <FactRow
            label="Historical Match"
            value={
              <span>
                <span className="text-gray-300">{String(facts.top_similar_disruption)}</span>
                {typeof facts.top_similar_score === 'number' && (
                  <span className="text-gray-500 ml-1">
                    ({facts.top_similar_score.toFixed(0)}% similar)
                  </span>
                )}
              </span>
            }
          />
        )}
      </div>
    </div>
  )
}

function AIUnavailableSection({ message }: { message: string }) {
  return (
    <div className="rounded-lg border border-gray-800 bg-gray-900/50 p-4">
      <SectionHeader
        label="AI Analysis"
        badge="IBM watsonx.ai"
        badgeColor="bg-gray-800 text-gray-500 border border-gray-700"
      />
      <div className="flex items-start gap-3">
        <span className="text-gray-600 text-lg mt-0.5" aria-hidden="true">⚙</span>
        <div>
          <p className="text-xs text-gray-500 leading-relaxed">{message}</p>
          <p className="text-[10px] text-gray-700 mt-2">
            Required:{' '}
            <code className="text-gray-600">WATSONX_API_KEY</code>,{' '}
            <code className="text-gray-600">WATSONX_PROJECT_ID</code>,{' '}
            <code className="text-gray-600">WATSONX_URL</code>
          </p>
        </div>
      </div>
    </div>
  )
}

function AIErrorSection({ errorDetail }: { errorDetail: string | null | undefined }) {
  return (
    <div className="rounded-lg border border-amber-900/40 bg-amber-950/10 p-4">
      <SectionHeader
        label="AI Analysis"
        badge="IBM watsonx.ai"
        badgeColor="bg-amber-900/30 text-amber-400 border border-amber-700/50"
      />
      <div className="flex items-start gap-3">
        <span className="text-amber-600 text-lg mt-0.5" aria-hidden="true">⚠</span>
        <div>
          <p className="text-xs text-amber-400/80">
            AI insights generation failed. System facts above remain accurate.
          </p>
          {errorDetail && (
            <p className="text-[10px] text-gray-600 mt-1">
              Error type: {errorDetail}
            </p>
          )}
        </div>
      </div>
    </div>
  )
}

function AIInsightsSection({
  data,
}: {
  data: NonNullable<AIInsightsResponse['insights']>
}) {
  return (
    <div className="rounded-lg border border-violet-900/40 bg-violet-950/10 p-4">
      <div className="flex items-center justify-between mb-3">
        <SectionHeader
          label="AI Analysis"
          badge="IBM watsonx.ai"
          badgeColor="bg-violet-900/30 text-violet-300 border border-violet-700/50"
        />
        <span className="text-[9px] text-gray-600 italic">
          AI-generated text — not operational metrics
        </span>
      </div>

      <div className="space-y-4">
        <div>
          <p className="text-[10px] font-semibold uppercase tracking-widest text-gray-500 mb-1">
            Disruption Explanation
          </p>
          <p className="text-xs text-gray-300 leading-relaxed">
            {data.disruption_explanation}
          </p>
        </div>

        <div>
          <p className="text-[10px] font-semibold uppercase tracking-widest text-gray-500 mb-1">
            Risk Summary
          </p>
          <p className="text-xs text-gray-300 leading-relaxed">
            {data.risk_summary}
          </p>
        </div>

        <div>
          <p className="text-[10px] font-semibold uppercase tracking-widest text-gray-500 mb-1">
            Decision Support
          </p>
          <p className="text-xs text-gray-300 leading-relaxed">
            {data.decision_support}
          </p>
        </div>

        {data.recommended_actions.length > 0 && (
          <div>
            <p className="text-[10px] font-semibold uppercase tracking-widest text-gray-500 mb-2">
              Recommended Actions
            </p>
            <ul className="space-y-1.5">
              {data.recommended_actions.map((action, i) => (
                <li key={i} className="flex items-start gap-2">
                  <span
                    className="shrink-0 w-4 h-4 rounded-full bg-violet-900/50 border border-violet-700/50
                               text-violet-400 text-[9px] font-bold flex items-center justify-center mt-0.5"
                  >
                    {i + 1}
                  </span>
                  <span className="text-xs text-gray-300 leading-relaxed">{action}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        <p className="text-[9px] text-gray-700 pt-1 border-t border-gray-800">
          Generated by {data.model_id} · IBM watsonx.ai ·{' '}
          Numerical values are from the deterministic SupplyShield engine only.
        </p>
      </div>
    </div>
  )
}

// ── Main component ─────────────────────────────────────────────────────────────

export function AIInsightsPanel({ disruptionId }: Props) {
  const [data, setData] = useState<AIInsightsResponse | null>(null)
  const [loading, setLoading] = useState(false)
  const [fetchError, setFetchError] = useState<string | null>(null)
  const [expanded, setExpanded] = useState(true)

  const load = useCallback(() => {
    setLoading(true)
    setFetchError(null)
    disruptionsApi
      .getAIInsights(disruptionId)
      .then(setData)
      .catch((e) => setFetchError(String(e)))
      .finally(() => setLoading(false))
  }, [disruptionId])

  useEffect(() => {
    load()
  }, [load])

  return (
    <div className="rounded-xl border border-gray-700 bg-gray-800 overflow-hidden">
      {/* Header */}
      <button
        onClick={() => setExpanded((v) => !v)}
        className="w-full flex items-center justify-between px-5 py-3.5
                   hover:bg-gray-750 transition-colors text-left"
      >
        <div className="flex items-center gap-2.5">
          <span className="text-sm font-semibold text-white">AI Decision Support</span>
          <span className="text-[10px] px-1.5 py-0.5 rounded bg-violet-900/40
                           border border-violet-700/40 text-violet-300 font-medium">
            IBM watsonx.ai
          </span>
          {data && (
            <span
              className={`text-[9px] px-1.5 py-0.5 rounded uppercase font-semibold ${
                data.status === 'available'
                  ? 'bg-green-900/40 text-green-400 border border-green-800'
                  : data.status === 'error'
                  ? 'bg-amber-900/40 text-amber-400 border border-amber-800'
                  : 'bg-gray-800 text-gray-500 border border-gray-700'
              }`}
            >
              {data.status}
            </span>
          )}
        </div>
        <div className="flex items-center gap-3">
          {!loading && !data && !fetchError && (
            <button
              onClick={(e) => { e.stopPropagation(); load() }}
              className="text-[11px] text-shield-400 hover:text-shield-300 px-2 py-0.5
                         rounded border border-shield-700/40 bg-shield-950/30"
            >
              Load insights
            </button>
          )}
          {loading && (
            <span className="text-[10px] text-gray-500 animate-pulse">Loading…</span>
          )}
          <span className="text-gray-600 text-sm">{expanded ? '▲' : '▼'}</span>
        </div>
      </button>

      {/* Body */}
      {expanded && (
        <div className="px-5 pb-5 pt-1 space-y-3">
          {/* Fetch-level error (network, 500, etc.) */}
          {fetchError && !loading && (
            <div className="rounded-lg border border-red-900/40 bg-red-950/20 px-4 py-3">
              <p className="text-xs text-red-400">
                Could not load AI panel: {fetchError}
              </p>
              <button
                onClick={load}
                className="mt-1.5 text-[11px] text-red-400/70 hover:text-red-300"
              >
                Retry
              </button>
            </div>
          )}

          {/* Loading state */}
          {loading && (
            <div className="space-y-3">
              {[80, 60, 90].map((w, i) => (
                <div
                  key={i}
                  className="h-3 bg-gray-700/50 rounded-full animate-pulse"
                  style={{ width: `${w}%` }}
                />
              ))}
            </div>
          )}

          {/* Content */}
          {!loading && data && (
            <>
              {/* System Facts — always shown */}
              <SystemFactsSection facts={data.system_facts} />

              {/* AI section — conditional on status */}
              {data.status === 'unavailable' && (
                <AIUnavailableSection message={data.message} />
              )}
              {data.status === 'error' && (
                <AIErrorSection errorDetail={data.error_detail} />
              )}
              {data.status === 'available' && data.insights && (
                <AIInsightsSection data={data.insights} />
              )}

              {/* Refresh button */}
              <div className="flex justify-end pt-1">
                <button
                  onClick={load}
                  className="text-[11px] text-gray-600 hover:text-gray-400 transition-colors"
                >
                  ↻ Refresh
                </button>
              </div>
            </>
          )}

          {/* Empty state */}
          {!loading && !data && !fetchError && (
            <p className="text-xs text-gray-600 text-center py-4">
              Click "Load insights" to fetch AI Decision Support data.
            </p>
          )}
        </div>
      )}
    </div>
  )
}
