"""add_disruption_dna

Revision ID: 6787dc4004f8
Revises: ecfcd27ae921
Create Date: 2026-09-15 16:36:44.366550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6787dc4004f8'
down_revision: Union[str, Sequence[str], None] = 'ecfcd27ae921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disruption_dna',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disruption_id', sa.Integer(), nullable=False),
    sa.Column('type_score', sa.Float(), nullable=False),
    sa.Column('type_label', sa.String(length=50), nullable=False),
    sa.Column('severity_score', sa.Float(), nullable=False),
    sa.Column('severity_raw', sa.Integer(), nullable=False),
    sa.Column('duration_score', sa.Float(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('geo_scope_score', sa.Float(), nullable=False),
    sa.Column('geo_scope_label', sa.String(length=30), nullable=False),
    sa.Column('transport_mode_score', sa.Float(), nullable=False),
    sa.Column('transport_mode_label', sa.String(length=30), nullable=False),
    sa.Column('capacity_impact_score', sa.Float(), nullable=False),
    sa.Column('port_relevance_score', sa.Float(), nullable=False),
    sa.Column('region_score', sa.Float(), nullable=False),
    sa.Column('region_label', sa.String(length=200), nullable=False),
    sa.Column('avg_impact_score', sa.Float(), nullable=False),
    sa.Column('affected_shipment_count', sa.Integer(), nullable=False),
    sa.Column('dna_summary', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['disruption_id'], ['disruptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disruption_dna_disruption_id'), 'disruption_dna', ['disruption_id'], unique=True)
    op.create_index(op.f('ix_disruption_dna_id'), 'disruption_dna', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disruption_dna_id'), table_name='disruption_dna')
    op.drop_index(op.f('ix_disruption_dna_disruption_id'), table_name='disruption_dna')
    op.drop_table('disruption_dna')
    # ### end Alembic commands ###
