"""initial_schema

Revision ID: ecfcd27ae921
Revises: 
Create Date: 2026-09-15 15:42:25.852065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecfcd27ae921'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requested_by', sa.String(length=200), nullable=False),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approval_status'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_id'), 'approvals', ['id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('disruptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disruption_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('WEATHER', 'PORT', 'SUPPLIER', 'GEOPOLITICAL', 'CYBER', 'DEMAND', 'TRANSPORT', 'REGULATORY', name='disruption_type'), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('affected_region', sa.String(length=200), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'MONITORING', 'RESOLVED', 'HISTORICAL', name='disruption_status'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disruption_code')
    )
    op.create_index(op.f('ix_disruptions_id'), 'disruptions', ['id'], unique=False)
    op.create_table('fleet_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_code', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('capacity_kg', sa.Float(), nullable=False),
    sa.Column('current_location', sa.String(length=200), nullable=False),
    sa.Column('current_lat', sa.Float(), nullable=False),
    sa.Column('current_lon', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'IN_TRANSIT', 'MAINTENANCE', 'RESERVED', name='vehicle_status'), nullable=False),
    sa.Column('available_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refrigerated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fleet_vehicles_id'), 'fleet_vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_fleet_vehicles_vehicle_code'), 'fleet_vehicles', ['vehicle_code'], unique=True)
    op.create_table('resilience_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_type', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.Enum('TIME', 'COST', 'TEMPERATURE', 'CAPACITY', name='wallet_dimension'), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('max_balance', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resilience_wallets_id'), 'resilience_wallets', ['id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_code', sa.String(length=20), nullable=False),
    sa.Column('route_name', sa.String(length=200), nullable=False),
    sa.Column('origin', sa.String(length=200), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('capacity_kg', sa.Float(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('transport_mode', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_code')
    )
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_table('rri_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('rri_value', sa.Float(), nullable=False),
    sa.Column('component_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rri_snapshots_computed_at'), 'rri_snapshots', ['computed_at'], unique=False)
    op.create_index(op.f('ix_rri_snapshots_entity_id'), 'rri_snapshots', ['entity_id'], unique=False)
    op.create_index(op.f('ix_rri_snapshots_entity_type'), 'rri_snapshots', ['entity_type'], unique=False)
    op.create_index(op.f('ix_rri_snapshots_id'), 'rri_snapshots', ['id'], unique=False)
    op.create_table('simulation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_type', sa.String(length=100), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rri_impact', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_runs_id'), 'simulation_runs', ['id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_code')
    )
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_table('recovery_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disruption_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_recovery_hours', sa.Float(), nullable=True),
    sa.Column('rri_recovery_projected', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='recovery_plan_status'), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['disruption_id'], ['disruptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_plans_id'), 'recovery_plans', ['id'], unique=False)
    op.create_table('resilience_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.Enum('TIME', 'COST', 'TEMPERATURE', 'CAPACITY', name='wallet_dimension'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['resilience_wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resilience_transactions_id'), 'resilience_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_resilience_transactions_wallet_id'), 'resilience_transactions', ['wallet_id'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_code', sa.String(length=20), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=200), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('cargo_type', sa.String(length=100), nullable=False),
    sa.Column('cargo_value_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('priority', sa.Enum('ROUTINE', 'STANDARD', 'HIGH', 'CRITICAL', name='cargo_priority'), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'IN_TRANSIT', 'DELAYED', 'AT_RISK', 'DELIVERED', 'CANCELLED', name='shipment_status'), nullable=False),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lon', sa.Float(), nullable=True),
    sa.Column('temperature_sensitive', sa.Boolean(), nullable=False),
    sa.Column('min_temperature_c', sa.Float(), nullable=True),
    sa.Column('max_temperature_c', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_id'), 'shipments', ['id'], unique=False)
    op.create_index(op.f('ix_shipments_shipment_code'), 'shipments', ['shipment_code'], unique=True)
    op.create_index(op.f('ix_shipments_supplier_id'), 'shipments', ['supplier_id'], unique=False)
    op.create_table('cold_chain_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.String(length=50), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_breach', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cold_chain_readings_id'), 'cold_chain_readings', ['id'], unique=False)
    op.create_index(op.f('ix_cold_chain_readings_recorded_at'), 'cold_chain_readings', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_cold_chain_readings_shipment_id'), 'cold_chain_readings', ['shipment_id'], unique=False)
    op.create_table('shipment_disruptions',
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('disruption_id', sa.Integer(), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.Column('delay_hours', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['disruption_id'], ['disruptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shipment_id', 'disruption_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_disruptions')
    op.drop_index(op.f('ix_cold_chain_readings_shipment_id'), table_name='cold_chain_readings')
    op.drop_index(op.f('ix_cold_chain_readings_recorded_at'), table_name='cold_chain_readings')
    op.drop_index(op.f('ix_cold_chain_readings_id'), table_name='cold_chain_readings')
    op.drop_table('cold_chain_readings')
    op.drop_index(op.f('ix_shipments_supplier_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_shipment_code'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_resilience_transactions_wallet_id'), table_name='resilience_transactions')
    op.drop_index(op.f('ix_resilience_transactions_id'), table_name='resilience_transactions')
    op.drop_table('resilience_transactions')
    op.drop_index(op.f('ix_recovery_plans_id'), table_name='recovery_plans')
    op.drop_table('recovery_plans')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_simulation_runs_id'), table_name='simulation_runs')
    op.drop_table('simulation_runs')
    op.drop_index(op.f('ix_rri_snapshots_id'), table_name='rri_snapshots')
    op.drop_index(op.f('ix_rri_snapshots_entity_type'), table_name='rri_snapshots')
    op.drop_index(op.f('ix_rri_snapshots_entity_id'), table_name='rri_snapshots')
    op.drop_index(op.f('ix_rri_snapshots_computed_at'), table_name='rri_snapshots')
    op.drop_table('rri_snapshots')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_resilience_wallets_id'), table_name='resilience_wallets')
    op.drop_table('resilience_wallets')
    op.drop_index(op.f('ix_fleet_vehicles_vehicle_code'), table_name='fleet_vehicles')
    op.drop_index(op.f('ix_fleet_vehicles_id'), table_name='fleet_vehicles')
    op.drop_table('fleet_vehicles')
    op.drop_index(op.f('ix_disruptions_id'), table_name='disruptions')
    op.drop_table('disruptions')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_approvals_id'), table_name='approvals')
    op.drop_table('approvals')
    # ### end Alembic commands ###
